---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ninjaspace
  name: ninjaspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: avocado-app
  name: avocado-app
  namespace: ninjaspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avocado-app
  template:
    metadata:
      labels:
        app: avocado-app
    spec:
      containers:
      - image: hashicorp/http-echo
        name: http-echo
        args:
        - "-text=This is the AVOCADO pod!"
---
kind: Service
apiVersion: v1
metadata:
  name: avocado-service
  namespace: ninjaspace
spec:
  selector:
    app: avocado-app
  ports:
    - port: 8080 
      targetPort: 5678 # Default port for image
---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: ninjaspace
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /avocado
          pathType: Prefix
          backend:
            service:
              name: avocado-service
              port:
                number: 8080