apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../resources/demo-deployment/
  - ../resources/kind-ingress-nginx/
  - github-source-auto.yaml

patches:
- target:
    kind: Deployment
    name: (.*-app)
    namespace: ninjaspace
  patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
    spec:
      replicas: 2