---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo1
  namespace: flux-system
spec:
  interval: 30s
  path: ./demo1
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-demo1
