---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-branch
  namespace: flux-system
spec:
  interval: 30s
  path: ./poc-git-tag
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-branch
