apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name:  github-branch
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m
  url: ssh://git@github.com/perbohler/flux-fleet-demo1
  ref:
    branch: git-branches
  secretRef:
    name: github-token
