---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: avocado-app
  name: avocado-app
  namespace: ninjaspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avocado-app
  template:
    metadata:
      labels:
        app: avocado-app
    spec:
      containers:
      - image: hashicorp/http-echo
        name: http-echo
        args:
        - "-text=This is the avocado Pod!"
---
kind: Service
apiVersion: v1
metadata:
  name: avocado-service
  namespace: ninjaspace
spec:
  selector:
    app: avocado-app
  ports:
    - port: 5678 # Default port for image
      targetPort: 5678