apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: fluxcd-priorityclass
value: 1000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for flux-cd service pods only."